// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxSelectAllController from "./checkbox_select_all_controller.js"
application.register("checkbox-select-all", CheckboxSelectAllController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import InfiniteScrollController from "./infinite_scroll_controller.js"
application.register("infinite-scroll", InfiniteScrollController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import PrettyJsonController from "./pretty_json_controller.js"
application.register("pretty-json", PrettyJsonController)

import TabsController from "./tabs_controller.js"
application.register("tabs", TabsController)

import TimeZoneController from "./time_zone_controller.js"
application.register("time-zone", TimeZoneController)
